version: '3'
services:
  web:
    image: final-project
    # deploy:
    #   replicas: 4
    #   restart_policy:
    #     condition: on-failure
    ports:
      - "3000:3000"
    networks:
      - webnet
    environment:
      - REDIS_HOST=redis
    depends_on:
      - mongo
      - websocket
      - messenger
      - users
  users:
    build: ./users.js
    port: "3001:3001"
  messenger:
    build: ./messenger.js
    port: "3002:3002"
  websocket:
    build: ./websocket.js
    port: "3003:3003"
  redis:
    image: redis:5.0.4
    ports:
      - "6379:6379"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - webnet
networks:
  webnet: