version: '3'
services:
  web:
    image: final-project
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    networks:
      - webnet
    environment:
      - REDIS_HOST=redis
    depends_on:
      - mongo
  
  redis:
    image: redis:5.0.4
    ports:
      - "6379:6379"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - webnet
networks:
  webnet: